# Site settings
title: Dodecaedro.mx
description: > # this means to ignore newlines until "baseurl:"
  En dodecaedro encontrarás arículos sobre la cultura del cine, literatura, artes plásticas, y música local mexicana.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dodecaedro.mx" # the base hostname & protocol for your site
permalink: pretty

# Build settings
markdown: kramdown

gems:
  - jekyll-sitemap

prose:
  rooturl: '_posts'
  siteurl: 'http://dodecaedro.mx'
  media: 'assets/img/posts'
  metadata:
    _posts/Cine/Reseñas:
      - name: "title"
        field:
          element: "text"
          label: "Título"
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "category"
        field:
          element: "hidden"
          value:
            - 'cine'
            - 'cine-resenas'
      - name: "thumbnail"
        field:
          element: "text"
          label: "Imagen de previsualización"
          help: "Copia la dirección de cualquier imagen en tu post"
          value: "assets/img/dummy.jpg"
      - name: "excerpt"
        field:
          element: "textarea"
          label: "Texto de previsualización"
          help: "NO USAR COMILLAS O GUIONES"
          value: "Por ejemplo > Cuando se posó frente a mí la luna, supe que todo estaba perdido..."
      - name: "author"
        field:
          element: "select"
          label: "Tu Nombre o Dodecaedro si es un trabajo en equipo."
          options:
            - name: "Dodecaedro"
              value: "Dodecaedro"
            - name: "Said Pulido"
              value: "Said Pulido"
            - name: "MGM"
              value: "MGM"
            - name: "Maro"
              value: "Maro"
            - name: "Sebastián Alfaro"
              value: "Sebastián Alfaro"
            - name: "Ramón Martínez Carrasco"
              value: "Ramón Martínez Carrasco"
            - name: "Sebastián López"
              value: "Sebastián López"
      - name: "tags"
        field:
          element: "textarea"
          label: "Agrega palabras relacionadas al contenido de tu post para que la gente lo encuentre en google"
          help: "Son como los hashtags pero en vez de #palabra es: palabra, ¡NO DEBES USAR GUIONES NI DOS PUNTOS!"
          value: "cine, cannes, director, etc, agrega, muchas,"
    _posts/Fotografía/Gifwalls:
      - name: "title"
        field:
          element: "text"
          label: "Título"
      - name: "layout"
        field:
          element: "hidden"
          value: "wall"
      - name: "category"
        field:
          element: "hidden"
          value:
            - 'foto'
            - 'foto-gifwalls'
      - name: "thumbnail"
        field:
          element: "text"
          label: "Imagen de previsualización"
          help: "Copia la dirección de cualquier imagen en tu post"
          value: "assets/img/dummy.jpg"
      - name: "excerpt"
        field:
          element: "textarea"
          label: "Texto de previsualización"
          help: "NO USAR COMILLAS O GUIONES"
          value: "Ejemplo: Cuando se posó frente a mí la luna, supe que todo estaba perdido..."
      - name: "author"
        field:
          element: "select"
          label: "Tu Nombre o Dodecaedro si es un trabajo en equipo."
          options:
            - name: "Dodecaedro"
              value: "Dodecaedro"
            - name: "Said Pulido"
              value: "Said Pulido"
            - name: "MGM"
              value: "MGM"
            - name: "Maro"
              value: "Maro"
            - name: "Sebastián Alfaro"
              value: "Sebastián Alfaro"
            - name: "Ramón Martínez Carrasco"
              value: "Ramón Martínez Carrasco"
            - name: "Sebastián López"
              value: "Sebastián López"
      - name: "tags"
        field:
          element: "textarea"
          label: "Agrega palabras relacionadas al contenido de tu post para que la gente lo encuentre en google"
          help: "Son como los hashtags pero en vez de #palabra es: palabra, ¡NO DEBES USAR GUIONES NI DOS PUNTOS!"
          value: "cine, cannes, director, etc, agrega, muchas,"
    _posts/Letras/Ensayos:
      - name: "title"
        field:
          element: "text"
          label: "Título"
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "category"
        field:
          element: "hidden"
          value: 
            - 'letras'
            - 'letras-ensayos'
      - name: "thumbnail"
        field:
          element: "text"
          label: "Imagen de previsualización"
          help: "Copia la dirección de cualquier imagen en tu post"
          value: "assets/img/dummy.jpg"
      - name: "excerpt"
        field:
          element: "textarea"
          label: "Texto de previsualización"
          help: "NO USAR COMILLAS O GUIONES"
          value: "Ejemplo: Cuando se posó frente a mí la luna, supe que todo estaba perdido..."
      - name: "author"
        field:
          element: "select"
          label: "Tu Nombre o Dodecaedro si es un trabajo en equipo."
          options:
            - name: "Dodecaedro"
              value: "Dodecaedro"
            - name: "Said Pulido"
              value: "Said Pulido"
            - name: "MGM"
              value: "MGM"
            - name: "Maro"
              value: "Maro"
            - name: "Sebastián Alfaro"
              value: "Sebastián Alfaro"
            - name: "Ramón Martínez Carrasco"
              value: "Ramón Martínez Carrasco"
            - name: "Sebastián López"
              value: "Sebastián López"
      - name: "tags"
        field:
          element: "textarea"
          label: "Agrega palabras relacionadas al contenido de tu post para que la gente lo encuentre en google"
          help: "Son como los hashtags pero en vez de #palabra es: palabra, ¡NO DEBES USAR GUIONES NI DOS PUNTOS!"
          value: "cine, cannes, director, etc, agrega, muchas,"
    _posts/Letras/Historias:
      - name: "title"
        field:
          element: "text"
          label: "Título"
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "category"
        field:
          element: "hidden"
          value: 
            - 'letras'
            - 'letras-historias'
      - name: "thumbnail"
        field:
          element: "text"
          label: "Imagen de previsualización"
          help: "Copia la dirección de cualquier imagen en tu post"
          value: "assets/img/dummy.jpg"
      - name: "excerpt"
        field:
          element: "textarea"
          label: "Texto de previsualización"
          help: "NO USAR COMILLAS O GUIONES"
          value: "Ejemplo: Cuando se posó frente a mí la luna, supe que todo estaba perdido..."
      - name: "author"
        field:
          element: "select"
          label: "Tu Nombre o Dodecaedro si es un trabajo en equipo."
          options:
            - name: "Dodecaedro"
              value: "Dodecaedro"
            - name: "Said Pulido"
              value: "Said Pulido"
            - name: "MGM"
              value: "MGM"
            - name: "Maro"
              value: "Maro"
            - name: "Sebastián Alfaro"
              value: "Sebastián Alfaro"
            - name: "Ramón Martínez Carrasco"
              value: "Ramón Martínez Carrasco"
            - name: "Sebastián López"
              value: "Sebastián López"
      - name: "tags"
        field:
          element: "textarea"
          label: "Agrega palabras relacionadas al contenido de tu post para que la gente lo encuentre en google"
          help: "Son como los hashtags pero en vez de #palabra es: palabra, ¡NO DEBES USAR GUIONES NI DOS PUNTOS!"
          value: "cine, cannes, director, etc, agrega, muchas,"
    _posts/Música/Reseñas:
      - name: "title"
        field:
          element: "text"
          label: "Título"
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "category"
        field:
          element: "hidden"
          value: 
            - 'musica'
            - 'musica-resenas'
      - name: "thumbnail"
        field:
          element: "text"
          label: "Imagen de previsualización"
          help: "Copia la dirección de cualquier imagen en tu post"
          value: "assets/img/dummy.jpg"
      - name: "excerpt"
        field:
          element: "textarea"
          label: "Texto de previsualización"
          help: "NO USAR COMILLAS DOS PUNTOS O GUIONES"
          value: "Ejemplo: Cuando se posó frente a mí la luna, supe que todo estaba perdido..."
      - name: "author"
        field:
          element: "select"
          label: "Tu Nombre o Dodecaedro si es un trabajo en equipo."
          options:
            - name: "Dodecaedro"
              value: "Dodecaedro"
            - name: "Said Pulido"
              value: "Said Pulido"
            - name: "MGM"
              value: "MGM"
            - name: "Maro"
              value: "Maro"
            - name: "Sebastián Alfaro"
              value: "Sebastián Alfaro"
            - name: "Ramón Martínez Carrasco"
              value: "Ramón Martínez Carrasco"
            - name: "Sebastián López"
              value: "Sebastián López"
      - name: "tags"
        field:
          element: "textarea"
          label: "Agrega palabras relacionadas al contenido de tu post para que la gente lo encuentre en google"
          help: "Son como los hashtags pero en vez de #palabra es: palabra, ¡NO DEBES USAR GUIONES NI DOS PUNTOS!"
          value: "cine, cannes, director, etc, agrega, muchas,"